"""
Unified configuration for the Finance crawler service.

Values can be overridden with environment variables so credentials do not have
to be hard-coded in the repository.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path


_PROJECT_DIR = Path(__file__).resolve().parents[2]


def _load_project_dotenv() -> None:
    """Load only MySQL connection settings from the project root .env file."""

    path = _PROJECT_DIR / ".env"
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip().lstrip("\ufeff")
        if not key.startswith("MYSQL_"):
            continue
        if key in os.environ:
            continue
        os.environ[key] = value.strip().strip('"').strip("'")


_load_project_dotenv()


def _env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


def _env_int(name: str, default: int) -> int:
    value = _env(name)
    return int(value) if value else default


def _env_float(name: str, default: float) -> float:
    value = _env(name)
    return float(value) if value else default


def _env_bool(name: str, default: bool = False) -> bool:
    value = _env(name)
    if not value:
        return default
    return value.lower() in {"1", "true", "yes", "y", "on"}


def _default_adb_path(project_dir: Path) -> str:
    bundled = project_dir / "platform-tools" / "adb.exe"
    if bundled.exists():
        return str(bundled)
    return shutil.which("adb") or "adb"


class Config:
    BASE_DIR = Path(__file__).resolve().parent
    PROJECT_DIR = _PROJECT_DIR

    # MySQL
    DB_HOST = _env("MYSQL_HOST", "localhost")
    DB_PORT = _env_int("MYSQL_PORT", 3306)
    DB_USER = _env("MYSQL_USER", "root")
    DB_PASSWORD = _env("MYSQL_PASSWORD", "")
    DB_NAME = _env("MYSQL_DATABASE", _env("MYSQL_APP_DATABASE", _env("CRAWLER_APP_DATABASE", "crawler_app")))
    CRAWLER_APP_DB_NAME = _env("MYSQL_APP_DATABASE", _env("CRAWLER_APP_DATABASE", DB_NAME))
    OPS_PLATFORM_DB_NAME = _env("MYSQL_OPS_DATABASE", _env("OPS_PLATFORM_DATABASE", "ops_platform"))
    DB_CONNECT_TIMEOUT = _env_int("MYSQL_CONNECT_TIMEOUT", 10)

    # Tencent Docs OpenAPI
    QQ_DOC_URL = _env("TENCENT_DOC_URL")
    QQ_FILE_ID = _env("TENCENT_DOC_FILE_ID")
    QQ_SHEET_ID = _env("TENCENT_DOC_SHEET_ID")
    QQ_READ_RANGE = _env("TENCENT_DOC_READ_RANGE", "A1:Q2000")
    QQ_SCAN_MODE = _env("TENCENT_DOC_SCAN_MODE", "today")
    QQ_SCAN_DATE = _env("TENCENT_DOC_SCAN_DATE", "")
    QQ_SHEET_TITLE_FILTER = _env("TENCENT_DOC_SHEET_TITLE_FILTER", "")
    QQ_POST_MARKET_TIME = _env("TENCENT_DOC_POST_MARKET_TIME", "15:30")

    QQ_ACCESS_TOKEN = _env("TENCENT_DOC_ACCESS_TOKEN")
    QQ_CLIENT_ID = _env("TENCENT_DOC_CLIENT_ID")
    QQ_CLIENT_SECRET = _env("TENCENT_DOC_CLIENT_SECRET")
    QQ_OPEN_ID = _env("TENCENT_DOC_OPEN_ID")
    QQ_TOKEN_URL = _env("TENCENT_DOC_TOKEN_URL", "https://docs.qq.com/oauth/v2/token")
    QQ_WRITE_DELAY = _env_float("TENCENT_DOC_WRITE_DELAY", 0.3)
    QQ_BATCH_UPDATE_SIZE = _env_int("TENCENT_DOC_BATCH_UPDATE_SIZE", 5)
    QQ_READ_CHUNK_ROWS = _env_int("TENCENT_DOC_READ_CHUNK_ROWS", 200)
    VALIDATE_DOC_ROW_BEFORE_WRITE = _env_bool("VALIDATE_DOC_ROW_BEFORE_WRITE", True)

    # Sheet column indexes, zero-based. Defaults match the test sheet:
    # J=post time, M=screenshot, N=post link, O=read count, P=comment count.
    QQ_COL_POST_TIME = _env_int("TENCENT_DOC_COL_POST_TIME", 9)
    QQ_COL_URL = _env_int("TENCENT_DOC_COL_URL", 13)
    QQ_COL_ACCOUNT_NAME = _env_int("TENCENT_DOC_COL_ACCOUNT_NAME", 11)
    QQ_COL_READ_COUNT = _env_int("TENCENT_DOC_COL_READ_COUNT", 14)
    QQ_COL_COMMENT_COUNT = _env_int("TENCENT_DOC_COL_COMMENT_COUNT", 15)
    QQ_COL_CHECK_STATUS = _env_int("TENCENT_DOC_COL_CHECK_STATUS", 16)
    QQ_COL_DETAIL_STATUS = _env_int("TENCENT_DOC_COL_DETAIL_STATUS", 16)
    QQ_COL_SCREENSHOT = _env_int("TENCENT_DOC_COL_SCREENSHOT", 12)
    SCREENSHOT_PUBLIC_BASE_URL = _env("SCREENSHOT_PUBLIC_BASE_URL", "")
    QQ_UPLOAD_SCREENSHOTS = _env_bool(
        "TENCENT_DOC_UPLOAD_SCREENSHOTS",
        _env_bool("TENCENT_DOC_ENABLE_IMAGE_UPLOAD", True),
    )
    QQ_IMAGE_INSERT_WIDTH = _env_float("TENCENT_DOC_IMAGE_INSERT_WIDTH", 160.0)
    QQ_IMAGE_INSERT_HEIGHT = _env_float("TENCENT_DOC_IMAGE_INSERT_HEIGHT", 300.0)
    QQ_IMAGE_UPLOAD_DELAY = _env_float("TENCENT_DOC_IMAGE_UPLOAD_DELAY", 0.25)
    QQ_IMAGE_UPLOAD_TIMEOUT = _env_int("TENCENT_DOC_IMAGE_UPLOAD_TIMEOUT", 30)

    # Polling and eligibility
    FETCH_INTERVAL_MINUTES = _env_int("FETCH_INTERVAL_MINUTES", 5)
    ENABLE_LEGACY_SCHEDULER_JOBS = _env_bool("ENABLE_LEGACY_SCHEDULER_JOBS", False)
    INITIAL_CHECK_DELAY_HOURS = _env_float("INITIAL_CHECK_DELAY_HOURS", 2.0)
    FETCH_ONLY_ELIGIBLE = _env_bool("FETCH_ONLY_ELIGIBLE", False)
    # 0 means import all discovered rows. Set a positive value for test runs.
    FETCH_LIMIT = _env_int("FETCH_LIMIT", 0)
    DETAIL_TIME = _env("DETAIL_TIME", "08:00")
    DETAIL_INTERVAL_MINUTES = _env_int("DETAIL_INTERVAL_MINUTES", 10)
    SUBMIT_WORKER_INTERVAL_SECONDS = _env_int("SUBMIT_WORKER_INTERVAL_SECONDS", 30)
    V2_CRAWL_WORKER_INTERVAL_SECONDS = _env_int("V2_CRAWL_WORKER_INTERVAL_SECONDS", 30)
    V2_WRITEBACK_WORKER_INTERVAL_SECONDS = _env_int("V2_WRITEBACK_WORKER_INTERVAL_SECONDS", 30)
    SCHEDULER_ROLES = _env("SCHEDULER_ROLES", "all")
    REPORT_TIME = _env("REPORT_TIME", "11:30")
    PROFILE_METRICS_DOC_URL = _env("PROFILE_METRICS_DOC_URL", "")
    PROFILE_METRICS_READ_RANGE = _env("PROFILE_METRICS_READ_RANGE", "A1:H2000")
    PROFILE_METRICS_TEMPLATE_RANGE = _env("PROFILE_METRICS_TEMPLATE_RANGE", "A2:H126")
    PROFILE_METRICS_DAILY_PREPARE_TIME = _env("PROFILE_METRICS_DAILY_PREPARE_TIME", "")
    PROFILE_METRICS_INTERVAL_MINUTES = _env_int("PROFILE_METRICS_INTERVAL_MINUTES", 0)
    PROFILE_METRICS_CRAWL_LIMIT = _env_int("PROFILE_METRICS_CRAWL_LIMIT", 0)
    PROFILE_METRICS_TARGET_DATE = _env("PROFILE_METRICS_TARGET_DATE", "")
    PROFILE_METRICS_WRITEBACK_ENABLED = _env_bool("PROFILE_METRICS_WRITEBACK_ENABLED", True)
    KOL_DAILY_SNAPSHOT_DOC_URL = _env("KOL_DAILY_SNAPSHOT_DOC_URL", "")
    KOL_DAILY_SNAPSHOT_WRITEBACK_DOC_URL = _env("KOL_DAILY_SNAPSHOT_WRITEBACK_DOC_URL", "")
    KOL_DAILY_SNAPSHOT_READ_RANGE = _env("KOL_DAILY_SNAPSHOT_READ_RANGE", "A1:H2000")
    KOL_DAILY_SNAPSHOT_TIME = _env("KOL_DAILY_SNAPSHOT_TIME", "22:00")
    KOL_DAILY_SNAPSHOT_WRITEBACK_DAYS = _env_int("KOL_DAILY_SNAPSHOT_WRITEBACK_DAYS", 1)
    KOL_DAILY_SNAPSHOT_SCHEDULE_TARGET_OFFSET_DAYS = _env_int(
        "KOL_DAILY_SNAPSHOT_SCHEDULE_TARGET_OFFSET_DAYS",
        1,
    )
    KOL_DAILY_SNAPSHOT_WRITEBACK_FONT_SIZE = _env_int("KOL_DAILY_SNAPSHOT_WRITEBACK_FONT_SIZE", 10)
    KOL_DAILY_CRAWL_TIME = _env("KOL_DAILY_CRAWL_TIME", "08:00")
    KOL_DAILY_CRAWL_LIMIT = _env_int("KOL_DAILY_CRAWL_LIMIT", 0)
    KOL_TENPAY_EXTERNAL_READS_SOURCE_DOC_URLS = _env("KOL_TENPAY_EXTERNAL_READS_SOURCE_DOC_URLS", "")
    KOL_TENPAY_EXTERNAL_READS_TARGET_DOC_URL = _env(
        "KOL_TENPAY_EXTERNAL_READS_TARGET_DOC_URL",
        "https://docs.qq.com/sheet/DYnhxS2VHZHBqR0V5?tab=wpvy0d",
    )
    KOL_TENPAY_EXTERNAL_READS_SOURCE_RANGE = _env("KOL_TENPAY_EXTERNAL_READS_SOURCE_RANGE", "A1:F5000")
    KOL_TENPAY_EXTERNAL_READS_TARGET_RANGE = _env("KOL_TENPAY_EXTERNAL_READS_TARGET_RANGE", "A1:I5000")
    KOL_TENPAY_EXTERNAL_READS_TIME = _env("KOL_TENPAY_EXTERNAL_READS_TIME", "06:00")
    KOL_TENPAY_EXTERNAL_READS_TARGET_PLATFORM = _env("KOL_TENPAY_EXTERNAL_READS_TARGET_PLATFORM", "理财通")
    KOL_TENPAY_EXTERNAL_READS_WRITEBACK_FONT_SIZE = _env_int("KOL_TENPAY_EXTERNAL_READS_WRITEBACK_FONT_SIZE", 10)
    PROFILE_POST_READ_CRAWL_LIMIT = _env_int("PROFILE_POST_READ_CRAWL_LIMIT", 0)
    PROFILE_POST_READ_MAX_SCROLLS = _env_int("PROFILE_POST_READ_MAX_SCROLLS", 5)
    PROFILE_POST_READ_MAX_POSTS = _env_int("PROFILE_POST_READ_MAX_POSTS", 3)
    ARTICLE_DETAILS_DOC_URL = _env("ARTICLE_DETAILS_DOC_URL", "")
    ARTICLE_DETAILS_READ_RANGE = _env("ARTICLE_DETAILS_READ_RANGE", "A1:O2000")
    ARTICLE_DETAILS_CRAWL_LIMIT = _env_int("ARTICLE_DETAILS_CRAWL_LIMIT", 0)
    ARTICLE_DETAILS_WRITEBACK_ENABLED = _env_bool("ARTICLE_DETAILS_WRITEBACK_ENABLED", True)
    DOC_LINK_READS_READ_RANGE = _env("DOC_LINK_READS_READ_RANGE", "A1:Q2000")
    DOC_LINK_READS_SHEET_TITLE = _env("DOC_LINK_READS_SHEET_TITLE", "")
    DOC_LINK_READS_CRAWL_LIMIT = _env_int("DOC_LINK_READS_CRAWL_LIMIT", 0)
    DOC_LINK_READS_ONLY_EMPTY = _env_bool("DOC_LINK_READS_ONLY_EMPTY", True)
    DOC_LINK_READS_LINK_COL = _env_int("DOC_LINK_READS_LINK_COL", 10)
    DOC_LINK_READS_READ_COL = _env_int("DOC_LINK_READS_READ_COL", 12)
    DOC_LINK_READS_ENABLE_OCR = _env_bool("DOC_LINK_READS_ENABLE_OCR", True)
    DOC_LINK_READS_OPEN_RETRIES = _env_int("DOC_LINK_READS_OPEN_RETRIES", 2)
    DOC_LINK_READS_RETRYABLE_COOLDOWN_SECONDS = _env_float("DOC_LINK_READS_RETRYABLE_COOLDOWN_SECONDS", 120.0)
    ANTFORTUNE_READ_COUNT_WARMUP_ENABLED = _env_bool("ANTFORTUNE_READ_COUNT_WARMUP_ENABLED", True)
    ANTFORTUNE_READ_COUNT_WARMUP_BEFORE_OPEN = _env_bool("ANTFORTUNE_READ_COUNT_WARMUP_BEFORE_OPEN", False)
    ANTFORTUNE_READ_COUNT_RECOVER_ON_RETRYABLE = _env_bool("ANTFORTUNE_READ_COUNT_RECOVER_ON_RETRYABLE", True)
    ANTFORTUNE_READ_COUNT_WARMUP_WAIT_SECONDS = _env_float("ANTFORTUNE_READ_COUNT_WARMUP_WAIT_SECONDS", 8.0)
    ANTFORTUNE_READ_COUNT_WARMUP_SWIPE_COUNT = _env_int("ANTFORTUNE_READ_COUNT_WARMUP_SWIPE_COUNT", 1)
    ANTFORTUNE_READ_COUNT_WARMUP_AFTER_SWIPE_SECONDS = _env_float(
        "ANTFORTUNE_READ_COUNT_WARMUP_AFTER_SWIPE_SECONDS",
        2.0,
    )

    ENABLE_CHECKER = _env_bool("ENABLE_CHECKER", True)
    CHECK_INTERVAL_MINUTES = _env_int("CHECK_INTERVAL_MINUTES", 10)
    CHECK_MAX_RETRIES = _env_int("CHECK_MAX_RETRIES", 3)
    DETAIL_MAX_RETRIES = _env_int("DETAIL_MAX_RETRIES", 2)
    DETAIL_REQUIRES_CHECK_SUCCESS = _env_bool("DETAIL_REQUIRES_CHECK_SUCCESS", True)
    DETAIL_NEXT_DAY_ONLY = _env_bool("DETAIL_NEXT_DAY_ONLY", True)
    DETAIL_SOURCE_DATES = _env("DETAIL_SOURCE_DATES", "")
    WRITEBACK_SINK_TYPE = _env("WRITEBACK_SINK_TYPE", "tencent_docs")
    WRITEBACK_EXCEL_PATH = _env("WRITEBACK_EXCEL_PATH", "")
    WRITEBACK_EXCEL_SAVE_AS = _env("WRITEBACK_EXCEL_SAVE_AS", "")
    WRITEBACK_EXCEL_SHEET_NAME = _env("WRITEBACK_EXCEL_SHEET_NAME", "")
    EXCEL_DETAIL_INPUT_PATH = _env("EXCEL_DETAIL_INPUT_PATH", "")
    EXCEL_DETAIL_OUTPUT_PATH = _env("EXCEL_DETAIL_OUTPUT_PATH", "")
    EXCEL_DETAIL_RESULT_JSONL_PATH = _env("EXCEL_DETAIL_RESULT_JSONL_PATH", "")
    EXCEL_DETAIL_SHEET_NAME = _env("EXCEL_DETAIL_SHEET_NAME", "")
    EXCEL_DETAIL_SOURCE_FILTER = _env("EXCEL_DETAIL_SOURCE_FILTER", "")
    EXCEL_DETAIL_ONLY_EMPTY = _env_bool("EXCEL_DETAIL_ONLY_EMPTY", True)
    EXCEL_DETAIL_SAVE_EVERY = _env_int("EXCEL_DETAIL_SAVE_EVERY", 1)
    EXCEL_DETAIL_COL_ACCOUNT_NAME = _env_int("EXCEL_DETAIL_COL_ACCOUNT_NAME", 9)
    EXCEL_DETAIL_COL_URL = _env_int("EXCEL_DETAIL_COL_URL", 10)
    EXCEL_DETAIL_COL_READ_COUNT = _env_int("EXCEL_DETAIL_COL_READ_COUNT", 11)
    EXCEL_DETAIL_COL_COMMENT_COUNT = _env_int("EXCEL_DETAIL_COL_COMMENT_COUNT", 12)
    EXCEL_DETAIL_COL_STATUS = _env_int("EXCEL_DETAIL_COL_STATUS", 14)
    EXCEL_DETAIL_COL_DURATION = _env_int("EXCEL_DETAIL_COL_DURATION", 15)
    EXCEL_DETAIL_COL_ERROR = _env_int("EXCEL_DETAIL_COL_ERROR", 16)
    EXCEL_DETAIL_COL_SOURCE = _env_int("EXCEL_DETAIL_COL_SOURCE", 17)
    CRAWL_MAX_TASK_SECONDS = _env_int("CRAWL_MAX_TASK_SECONDS", 0)
    CRAWL_MAX_CONSECUTIVE_ERRORS = _env_int("CRAWL_MAX_CONSECUTIVE_ERRORS", 5)
    TASK_RUNNING_TIMEOUT_MINUTES = _env_int("TASK_RUNNING_TIMEOUT_MINUTES", 360)
    URL_RESOLVE_WORKERS = _env_int("URL_RESOLVE_WORKERS", 4)
    CRAWL_ACTIVE_START = _env("CRAWL_ACTIVE_START", "")
    CRAWL_ACTIVE_END = _env("CRAWL_ACTIVE_END", "")

    # ADB / device
    ADB_PATH = _env("ADB_PATH", _default_adb_path(PROJECT_DIR))
    DEVICE_SERIAL = _env("DEVICE_SERIAL", "")
    DEVICE_CHECK_TIMEOUT = _env_int("DEVICE_CHECK_TIMEOUT", 8)
    DEVICE_HEALTH_CACHE_SECONDS = _env_float("DEVICE_HEALTH_CACHE_SECONDS", 8.0)
    DEVICE_PREPARE_INTERVAL_SECONDS = _env_float("DEVICE_PREPARE_INTERVAL_SECONDS", 120.0)
    DEVICE_AUTO_RECONNECT = _env_bool("DEVICE_AUTO_RECONNECT", True)
    DEVICE_RECONNECT_RETRIES = _env_int("DEVICE_RECONNECT_RETRIES", 3)
    DEVICE_RECONNECT_DELAY_SECONDS = _env_float("DEVICE_RECONNECT_DELAY_SECONDS", 2.0)
    DEVICE_POOL_ENABLED = _env_bool("DEVICE_POOL_ENABLED", True)
    DEVICE_LEASE_SECONDS = _env_int("DEVICE_LEASE_SECONDS", 900)
    DEVICE_RISK_COOLDOWN_SECONDS = _env_int("DEVICE_RISK_COOLDOWN_SECONDS", 1800)
    DEVICE_UNAVAILABLE_COOLDOWN_SECONDS = _env_int("DEVICE_UNAVAILABLE_COOLDOWN_SECONDS", 300)
    DEVICE_LOGIN_COOLDOWN_SECONDS = _env_int("DEVICE_LOGIN_COOLDOWN_SECONDS", 86400)
    ALIPAY_PACKAGE = "com.eg.android.AlipayGphone"
    AFWEALTH_PACKAGE = "com.antfortune.wealth"
    TENPAY_PACKAGE = _env("TENPAY_PACKAGE", "com.tencent.fortuneplat")

    # Crawl behavior
    POST_DELAY_MIN = _env_float("POST_DELAY_MIN", 2.0)
    POST_DELAY_MAX = _env_float("POST_DELAY_MAX", 4.5)
    READ_COUNT_POST_DELAY_MIN = _env_float("READ_COUNT_POST_DELAY_MIN", 20.0)
    READ_COUNT_POST_DELAY_MAX = _env_float("READ_COUNT_POST_DELAY_MAX", 45.0)
    SCROLL_TIMES = _env_int("SCROLL_TIMES", 2)
    DETAIL_MAX_CAPTURE_PAGES = _env_int("DETAIL_MAX_CAPTURE_PAGES", 3)
    PAGE_LOAD_WAIT = _env_float("PAGE_LOAD_WAIT", 3.0)
    PAGE_STATUS_READY_TIMEOUT = _env_float("PAGE_STATUS_READY_TIMEOUT", 8.0)
    PAGE_STATUS_READY_INTERVAL = _env_float("PAGE_STATUS_READY_INTERVAL", 1.0)
    APP_OPEN_RECOVERY_RETRIES = _env_int("APP_OPEN_RECOVERY_RETRIES", 1)
    APP_RESTART_WAIT = _env_float("APP_RESTART_WAIT", 2.0)
    DETAIL_BLANK_REOPEN_RETRIES = _env_int("DETAIL_BLANK_REOPEN_RETRIES", 2)
    DETAIL_BLANK_REOPEN_WAIT = _env_float("DETAIL_BLANK_REOPEN_WAIT", 2.0)
    DETAIL_POST_DELAY_MIN = _env_float("DETAIL_POST_DELAY_MIN", 1.0)
    DETAIL_POST_DELAY_MAX = _env_float("DETAIL_POST_DELAY_MAX", 2.0)
    DETAIL_SCROLL_WAIT = _env_float("DETAIL_SCROLL_WAIT", 0.8)
    DETAIL_ENABLE_OCR = _env_bool("DETAIL_ENABLE_OCR", True)
    OCR_MIN_CONFIDENCE = _env_float("OCR_MIN_CONFIDENCE", 30.0)

    # Files
    SCREENSHOT_DIR = BASE_DIR / "screenshots"
    LOG_DIR = BASE_DIR / "logs"
    CAPTURE_DIR = BASE_DIR / "captures"
    REPORT_DIR = BASE_DIR / "reports"
    EXPORT_DIR = BASE_DIR / "exports"
    CACHE_FILE = BASE_DIR / _env("APP_SCHEME_CACHE_FILE", ".app_scheme_cache.json")
    TOKEN_CACHE_FILE = BASE_DIR / ".qq_token_cache.json"
    LATEST_CANDIDATES_FILE = EXPORT_DIR / "latest_candidates.json"
    ALERT_LOG_FILE = LOG_DIR / "alerts.jsonl"

    # Reports
    READ_COUNT_THRESHOLD = _env_int("READ_COUNT_THRESHOLD", 30)
    REPORT_TOP_N = _env_int("REPORT_TOP_N", 3)
    TENCENT_DOC_REPORT_SHEET_TITLE = _env("TENCENT_DOC_REPORT_SHEET_TITLE", "内部数据报告")

    # Alerts and supervision
    ALERT_ENABLED = _env_bool("ALERT_ENABLED", True)
    ALERT_WEBHOOK_URL = _env("ALERT_WEBHOOK_URL", "")
    ALERT_MIN_INTERVAL_SECONDS = _env_int("ALERT_MIN_INTERVAL_SECONDS", 300)
    HEARTBEAT_INTERVAL_MINUTES = _env_int("HEARTBEAT_INTERVAL_MINUTES", 30)
    SUPERVISOR_RESTART_DELAY_SECONDS = _env_int("SUPERVISOR_RESTART_DELAY_SECONDS", 10)
    SUPERVISOR_MAX_RESTARTS = _env_int("SUPERVISOR_MAX_RESTARTS", 0)


for path in [
    Config.SCREENSHOT_DIR,
    Config.LOG_DIR,
    Config.CAPTURE_DIR,
    Config.REPORT_DIR,
    Config.EXPORT_DIR,
]:
    path.mkdir(parents=True, exist_ok=True)
