$env:TENCENT_DOC_URL = "https://docs.qq.com/sheet/DY1hCSG96TkVySmp1?tab=BB08J2"
$env:TENCENT_DOC_FILE_ID = "DY1hCSG96TkVySmp1"
$env:TENCENT_DOC_SHEET_ID = "BB08J2"
$env:TENCENT_DOC_READ_RANGE = "A1:P625"

$env:TENCENT_DOC_CLIENT_ID = "your-client-id"
$env:TENCENT_DOC_OPEN_ID = "your-open-id"
$env:TENCENT_DOC_ACCESS_TOKEN = "your-access-token"
# Optional: used only when ACCESS_TOKEN is not set.
$env:TENCENT_DOC_CLIENT_SECRET = "your-client-secret"

$env:MYSQL_HOST = "localhost"
$env:MYSQL_PORT = "3306"
$env:MYSQL_USER = "root"
$env:MYSQL_PASSWORD = "your-mysql-password"
$env:MYSQL_DATABASE = "post_supplement_lib"

$env:ADB_PATH = "D:\Code\adb\platform-tools\adb.exe"
$env:DEVICE_SERIAL = "your-adb-device-serial"

$env:FETCH_INTERVAL_MINUTES = "5"
$env:CHECK_INTERVAL_MINUTES = "10"
$env:POST_ELIGIBLE_HOURS = "2"
$env:FETCH_LIMIT = "10"
$env:BATCH_LIMIT = "0"
$env:BATCH_TIME = "10:00"
$env:REPORT_TIME = "11:30"
$env:SCROLL_TIMES = "2"
$env:BATCH_MAX_CAPTURE_PAGES = "3"
$env:BATCH_ENABLE_OCR = "true"
$env:OCR_MIN_CONFIDENCE = "30"
$env:PAGE_LOAD_WAIT = "3.0"
$env:BATCH_POST_DELAY_MIN = "1.0"
$env:BATCH_POST_DELAY_MAX = "2.0"
$env:BATCH_SCROLL_WAIT = "0.8"
$env:MAX_POSTS_PER_RUN = "0"
$env:CRAWL_MAX_TASK_SECONDS = "0"
$env:CRAWL_MAX_CONSECUTIVE_ERRORS = "5"
$env:URL_RESOLVE_WORKERS = "4"
$env:CRAWL_ACTIVE_START = ""
$env:CRAWL_ACTIVE_END = ""
$env:DEVICE_CHECK_TIMEOUT = "8"
$env:DEVICE_HEALTH_CACHE_SECONDS = "8"
$env:DEVICE_PREPARE_INTERVAL_SECONDS = "120"

# Zero-based column indexes in the test sheet:
# J=post time, L=account/check result, N=post URL, O=read count, P=comment count, Q=batch status.
$env:TENCENT_DOC_COL_POST_TIME = "9"
$env:TENCENT_DOC_COL_ACCOUNT_NAME = "11"
$env:TENCENT_DOC_COL_URL = "13"
$env:TENCENT_DOC_COL_READ_COUNT = "14"
$env:TENCENT_DOC_COL_COMMENT_COUNT = "15"
$env:TENCENT_DOC_COL_BATCH_STATUS = "16"
$env:TENCENT_DOC_COL_SCREENSHOT = "17"
$env:SCREENSHOT_PUBLIC_BASE_URL = ""
$env:TENCENT_DOC_UPLOAD_SCREENSHOTS = "true"
$env:TENCENT_DOC_IMAGE_INSERT_WIDTH = "160"
$env:TENCENT_DOC_IMAGE_INSERT_HEIGHT = "300"
$env:TENCENT_DOC_IMAGE_UPLOAD_DELAY = "0.25"

$env:ENABLE_CHECKER = "true"
$env:BATCH_REQUIRES_CHECK_SUCCESS = "true"
$env:BATCH_NEXT_DAY_ONLY = "true"
$env:USE_TASK_SUBMISSIONS_FOR_BATCH = "true"
$env:VALIDATE_DOC_ROW_BEFORE_WRITE = "true"
$env:WRITEBACK_SINK_TYPE = "tencent_docs"
$env:WRITEBACK_EXCEL_PATH = ""
$env:WRITEBACK_EXCEL_SAVE_AS = ""
$env:WRITEBACK_EXCEL_SHEET_NAME = ""

# Local Excel direct batch mode. This mode reads links from Excel, crawls them
# directly, writes results to a workbook, and records submissions/executions.
$env:EXCEL_BATCH_INPUT_PATH = "D:\demo\5月20日.xlsx"
$env:EXCEL_BATCH_OUTPUT_PATH = "D:\demo\5月20日_batch_output.xlsx"
$env:EXCEL_BATCH_RESULT_JSONL_PATH = "D:\demo\5月20日_batch_results.jsonl"
$env:EXCEL_BATCH_SHEET_NAME = ""
$env:EXCEL_BATCH_SOURCE_FILTER = ""
$env:EXCEL_BATCH_ONLY_EMPTY = "true"
$env:EXCEL_BATCH_LIMIT = "0"
$env:EXCEL_BATCH_ALIPAY_LIMIT = "0"
$env:EXCEL_BATCH_ANTFORTUNE_LIMIT = "0"
$env:EXCEL_BATCH_TENPAY_LIMIT = "0"
$env:EXCEL_BATCH_SAVE_EVERY = "1"
# Zero-based Excel columns. Defaults match: J=account, K=url, L=read, M=comment.
$env:EXCEL_BATCH_COL_ACCOUNT_NAME = "9"
$env:EXCEL_BATCH_COL_URL = "10"
$env:EXCEL_BATCH_COL_READ_COUNT = "11"
$env:EXCEL_BATCH_COL_COMMENT_COUNT = "12"
$env:EXCEL_BATCH_COL_STATUS = "14"
$env:EXCEL_BATCH_COL_DURATION = "15"
$env:EXCEL_BATCH_COL_ERROR = "16"
$env:EXCEL_BATCH_COL_SOURCE = "17"
$env:TENCENT_DOC_BATCH_UPDATE_SIZE = "5"
$env:TENCENT_DOC_WRITE_DELAY = "0.3"

$env:ALERT_ENABLED = "true"
$env:ALERT_WEBHOOK_URL = ""
$env:ALERT_MIN_INTERVAL_SECONDS = "300"
$env:HEARTBEAT_INTERVAL_MINUTES = "30"
$env:SUPERVISOR_RESTART_DELAY_SECONDS = "10"
$env:SUPERVISOR_MAX_RESTARTS = "0"
